// Generated by gencpp from file nebulizador_arm/JointMove_actionGoal.msg
// DO NOT EDIT!


#ifndef NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONGOAL_H
#define NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nebulizador_arm
{
template <class ContainerAllocator>
struct JointMove_actionGoal_
{
  typedef JointMove_actionGoal_<ContainerAllocator> Type;

  JointMove_actionGoal_()
    : count(0.0)
    , name()  {
    }
  JointMove_actionGoal_(const ContainerAllocator& _alloc)
    : count(0.0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef float _count_type;
  _count_type count;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointMove_actionGoal_

typedef ::nebulizador_arm::JointMove_actionGoal_<std::allocator<void> > JointMove_actionGoal;

typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionGoal > JointMove_actionGoalPtr;
typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionGoal const> JointMove_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator1> & lhs, const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator1> & lhs, const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nebulizador_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc9dc3309c69f8191838c2d4b6392c4c";
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc9dc3309c69f819ULL;
  static const uint64_t static_value2 = 0x1838c2d4b6392c4cULL;
};

template<class ContainerAllocator>
struct DataType< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nebulizador_arm/JointMove_actionGoal";
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"float32 count\n"
"string name\n"
;
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMove_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nebulizador_arm::JointMove_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<float>::stream(s, indent + "  ", v.count);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONGOAL_H
