// Generated by gencpp from file nebulizador_arm/JointMove_actionFeedback.msg
// DO NOT EDIT!


#ifndef NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONFEEDBACK_H
#define NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nebulizador_arm
{
template <class ContainerAllocator>
struct JointMove_actionFeedback_
{
  typedef JointMove_actionFeedback_<ContainerAllocator> Type;

  JointMove_actionFeedback_()
    : current_number(0.0)  {
    }
  JointMove_actionFeedback_(const ContainerAllocator& _alloc)
    : current_number(0.0)  {
  (void)_alloc;
    }



   typedef float _current_number_type;
  _current_number_type current_number;





  typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct JointMove_actionFeedback_

typedef ::nebulizador_arm::JointMove_actionFeedback_<std::allocator<void> > JointMove_actionFeedback;

typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionFeedback > JointMove_actionFeedbackPtr;
typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionFeedback const> JointMove_actionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator1> & lhs, const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_number == rhs.current_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator1> & lhs, const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nebulizador_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfbf7afee89443c0d6ddfe8c2c044afe";
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfbf7afee89443c0ULL;
  static const uint64_t static_value2 = 0xd6ddfe8c2c044afeULL;
};

template<class ContainerAllocator>
struct DataType< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nebulizador_arm/JointMove_actionFeedback";
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 current_number\n"
;
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMove_actionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nebulizador_arm::JointMove_actionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_number: ";
    Printer<float>::stream(s, indent + "  ", v.current_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONFEEDBACK_H
