// Generated by gencpp from file nebulizador_arm/JointMove_actionResult.msg
// DO NOT EDIT!


#ifndef NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONRESULT_H
#define NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nebulizador_arm
{
template <class ContainerAllocator>
struct JointMove_actionResult_
{
  typedef JointMove_actionResult_<ContainerAllocator> Type;

  JointMove_actionResult_()
    : final_count(0.0)  {
    }
  JointMove_actionResult_(const ContainerAllocator& _alloc)
    : final_count(0.0)  {
  (void)_alloc;
    }



   typedef float _final_count_type;
  _final_count_type final_count;





  typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct JointMove_actionResult_

typedef ::nebulizador_arm::JointMove_actionResult_<std::allocator<void> > JointMove_actionResult;

typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionResult > JointMove_actionResultPtr;
typedef boost::shared_ptr< ::nebulizador_arm::JointMove_actionResult const> JointMove_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator1> & lhs, const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_count == rhs.final_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator1> & lhs, const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nebulizador_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b77524ca8766678c51227d7ae221c47";
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b77524ca8766678ULL;
  static const uint64_t static_value2 = 0xc51227d7ae221c47ULL;
};

template<class ContainerAllocator>
struct DataType< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nebulizador_arm/JointMove_actionResult";
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"float32 final_count\n"
;
  }

  static const char* value(const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMove_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nebulizador_arm::JointMove_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "final_count: ";
    Printer<float>::stream(s, indent + "  ", v.final_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEBULIZADOR_ARM_MESSAGE_JOINTMOVE_ACTIONRESULT_H
