nebulizador_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  link1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  link2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}