(cl:defpackage nebulizador_arm-msg
  (:use )
  (:export
   "<JOINTMOVE_ACTIONACTION>"
   "JOINTMOVE_ACTIONACTION"
   "<JOINTMOVE_ACTIONACTIONFEEDBACK>"
   "JOINTMOVE_ACTIONACTIONFEEDBACK"
   "<JOINTMOVE_ACTIONACTIONGOAL>"
   "JOINTMOVE_ACTIONACTIONGOAL"
   "<JOINTMOVE_ACTIONACTIONRESULT>"
   "JOINTMOVE_ACTIONACTIONRESULT"
   "<JOINTMOVE_ACTIONFEEDBACK>"
   "JOINTMOVE_ACTIONFEEDBACK"
   "<JOINTMOVE_ACTIONGOAL>"
   "JOINTMOVE_ACTIONGOAL"
   "<JOINTMOVE_ACTIONRESULT>"
   "JOINTMOVE_ACTIONRESULT"
  ))

