; Auto-generated. Do not edit!


(cl:in-package nebulizador_arm-msg)


;//! \htmlinclude JointMove_actionActionGoal.msg.html

(cl:defclass <JointMove_actionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type nebulizador_arm-msg:JointMove_actionGoal
    :initform (cl:make-instance 'nebulizador_arm-msg:JointMove_actionGoal)))
)

(cl:defclass JointMove_actionActionGoal (<JointMove_actionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointMove_actionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointMove_actionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nebulizador_arm-msg:<JointMove_actionActionGoal> is deprecated: use nebulizador_arm-msg:JointMove_actionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <JointMove_actionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:header-val is deprecated.  Use nebulizador_arm-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <JointMove_actionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:goal_id-val is deprecated.  Use nebulizador_arm-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <JointMove_actionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:goal-val is deprecated.  Use nebulizador_arm-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointMove_actionActionGoal>) ostream)
  "Serializes a message object of type '<JointMove_actionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointMove_actionActionGoal>) istream)
  "Deserializes a message object of type '<JointMove_actionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointMove_actionActionGoal>)))
  "Returns string type for a message object of type '<JointMove_actionActionGoal>"
  "nebulizador_arm/JointMove_actionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointMove_actionActionGoal)))
  "Returns string type for a message object of type 'JointMove_actionActionGoal"
  "nebulizador_arm/JointMove_actionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointMove_actionActionGoal>)))
  "Returns md5sum for a message object of type '<JointMove_actionActionGoal>"
  "ea41c1ea6ee29b7cd3a594fd5703b39f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointMove_actionActionGoal)))
  "Returns md5sum for a message object of type 'JointMove_actionActionGoal"
  "ea41c1ea6ee29b7cd3a594fd5703b39f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointMove_actionActionGoal>)))
  "Returns full string definition for message of type '<JointMove_actionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%JointMove_actionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: nebulizador_arm/JointMove_actionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 count~%string name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointMove_actionActionGoal)))
  "Returns full string definition for message of type 'JointMove_actionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%JointMove_actionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: nebulizador_arm/JointMove_actionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 count~%string name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointMove_actionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointMove_actionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JointMove_actionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
