; Auto-generated. Do not edit!


(cl:in-package nebulizador_arm-msg)


;//! \htmlinclude JointMove_actionGoal.msg.html

(cl:defclass <JointMove_actionGoal> (roslisp-msg-protocol:ros-message)
  ((count
    :reader count
    :initarg :count
    :type cl:float
    :initform 0.0)
   (name
    :reader name
    :initarg :name
    :type cl:string
    :initform ""))
)

(cl:defclass JointMove_actionGoal (<JointMove_actionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointMove_actionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointMove_actionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nebulizador_arm-msg:<JointMove_actionGoal> is deprecated: use nebulizador_arm-msg:JointMove_actionGoal instead.")))

(cl:ensure-generic-function 'count-val :lambda-list '(m))
(cl:defmethod count-val ((m <JointMove_actionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:count-val is deprecated.  Use nebulizador_arm-msg:count instead.")
  (count m))

(cl:ensure-generic-function 'name-val :lambda-list '(m))
(cl:defmethod name-val ((m <JointMove_actionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:name-val is deprecated.  Use nebulizador_arm-msg:name instead.")
  (name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointMove_actionGoal>) ostream)
  "Serializes a message object of type '<JointMove_actionGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'count))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointMove_actionGoal>) istream)
  "Deserializes a message object of type '<JointMove_actionGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'count) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointMove_actionGoal>)))
  "Returns string type for a message object of type '<JointMove_actionGoal>"
  "nebulizador_arm/JointMove_actionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointMove_actionGoal)))
  "Returns string type for a message object of type 'JointMove_actionGoal"
  "nebulizador_arm/JointMove_actionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointMove_actionGoal>)))
  "Returns md5sum for a message object of type '<JointMove_actionGoal>"
  "bc9dc3309c69f8191838c2d4b6392c4c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointMove_actionGoal)))
  "Returns md5sum for a message object of type 'JointMove_actionGoal"
  "bc9dc3309c69f8191838c2d4b6392c4c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointMove_actionGoal>)))
  "Returns full string definition for message of type '<JointMove_actionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 count~%string name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointMove_actionGoal)))
  "Returns full string definition for message of type 'JointMove_actionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 count~%string name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointMove_actionGoal>))
  (cl:+ 0
     4
     4 (cl:length (cl:slot-value msg 'name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointMove_actionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'JointMove_actionGoal
    (cl:cons ':count (count msg))
    (cl:cons ':name (name msg))
))
