; Auto-generated. Do not edit!


(cl:in-package nebulizador_arm-msg)


;//! \htmlinclude JointMove_actionFeedback.msg.html

(cl:defclass <JointMove_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((current_number
    :reader current_number
    :initarg :current_number
    :type cl:float
    :initform 0.0))
)

(cl:defclass JointMove_actionFeedback (<JointMove_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointMove_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointMove_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nebulizador_arm-msg:<JointMove_actionFeedback> is deprecated: use nebulizador_arm-msg:JointMove_actionFeedback instead.")))

(cl:ensure-generic-function 'current_number-val :lambda-list '(m))
(cl:defmethod current_number-val ((m <JointMove_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:current_number-val is deprecated.  Use nebulizador_arm-msg:current_number instead.")
  (current_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointMove_actionFeedback>) ostream)
  "Serializes a message object of type '<JointMove_actionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_number))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointMove_actionFeedback>) istream)
  "Deserializes a message object of type '<JointMove_actionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_number) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointMove_actionFeedback>)))
  "Returns string type for a message object of type '<JointMove_actionFeedback>"
  "nebulizador_arm/JointMove_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointMove_actionFeedback)))
  "Returns string type for a message object of type 'JointMove_actionFeedback"
  "nebulizador_arm/JointMove_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointMove_actionFeedback>)))
  "Returns md5sum for a message object of type '<JointMove_actionFeedback>"
  "dfbf7afee89443c0d6ddfe8c2c044afe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointMove_actionFeedback)))
  "Returns md5sum for a message object of type 'JointMove_actionFeedback"
  "dfbf7afee89443c0d6ddfe8c2c044afe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointMove_actionFeedback>)))
  "Returns full string definition for message of type '<JointMove_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointMove_actionFeedback)))
  "Returns full string definition for message of type 'JointMove_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 current_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointMove_actionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointMove_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'JointMove_actionFeedback
    (cl:cons ':current_number (current_number msg))
))
