; Auto-generated. Do not edit!


(cl:in-package nebulizador_arm-msg)


;//! \htmlinclude JointMove_actionResult.msg.html

(cl:defclass <JointMove_actionResult> (roslisp-msg-protocol:ros-message)
  ((final_count
    :reader final_count
    :initarg :final_count
    :type cl:float
    :initform 0.0))
)

(cl:defclass JointMove_actionResult (<JointMove_actionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointMove_actionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointMove_actionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nebulizador_arm-msg:<JointMove_actionResult> is deprecated: use nebulizador_arm-msg:JointMove_actionResult instead.")))

(cl:ensure-generic-function 'final_count-val :lambda-list '(m))
(cl:defmethod final_count-val ((m <JointMove_actionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nebulizador_arm-msg:final_count-val is deprecated.  Use nebulizador_arm-msg:final_count instead.")
  (final_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointMove_actionResult>) ostream)
  "Serializes a message object of type '<JointMove_actionResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_count))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointMove_actionResult>) istream)
  "Deserializes a message object of type '<JointMove_actionResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_count) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointMove_actionResult>)))
  "Returns string type for a message object of type '<JointMove_actionResult>"
  "nebulizador_arm/JointMove_actionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointMove_actionResult)))
  "Returns string type for a message object of type 'JointMove_actionResult"
  "nebulizador_arm/JointMove_actionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointMove_actionResult>)))
  "Returns md5sum for a message object of type '<JointMove_actionResult>"
  "2b77524ca8766678c51227d7ae221c47")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointMove_actionResult)))
  "Returns md5sum for a message object of type 'JointMove_actionResult"
  "2b77524ca8766678c51227d7ae221c47")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointMove_actionResult>)))
  "Returns full string definition for message of type '<JointMove_actionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 final_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointMove_actionResult)))
  "Returns full string definition for message of type 'JointMove_actionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32 final_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointMove_actionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointMove_actionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JointMove_actionResult
    (cl:cons ':final_count (final_count msg))
))
